"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-+1j-)k8ty37^qmg2l-c8btu$kui3pmpg76w&#v-8-jdl-z&3e_')

# SECURITY WARNING: don't run with debug turned on in production!
ENVIRONMENT = config('ENVIRONMENT', default='development')
DEBUG = config('DEBUG', default=ENVIRONMENT == 'development', cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=lambda v: [s.strip() for s in v.split(',')])

# CSRF
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://*,https://*',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# CORS
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)

# Cookie-lərin frontend ilə işləməsi üçün
CORS_ALLOW_CREDENTIALS = True
INSTALLED_APPS = [
    'jazzmin',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',       
    'rest_framework.authtoken',

    'psychologyApp',
    'authApp',
    'drf_yasg',
    "corsheaders",
    "payments",
    "licenses"
]

JAZZMIN_SETTINGS = {
    "site_title": "Psychology admin",
    "site_header": "Psychology admin",
    "site_brand": "Psychology admin",
    "login_logo": "images/logo.png",
    "site_logo": "images/logoS.png",
    
    "show_ui_builder": True,
  "icons": {
        "authApp.CustomUser": "fas fa-user",
        "authApp.Contact": "fas fa-address-book",
        "authApp.ContactInfo": "fas fa-info-circle",
        "authApp.About": "fas fa-file-alt",
        "authApp.Plan": "fas fa-clipboard-list",
        "authApp.Tag": "fas fa-tag",
        "authApp.Blog": "fas fa-blog",
        "psychologyApp.Question": "fas fa-question-circle",
        "psychologyApp.Test": "fas fa-vial",
        "psychologyApp.Answer": "fas fa-check-square",
        "psychologyApp.PersonalityType": "fas fa-user",
        "payments.Payment": "fas fa-credit-card",
        "licenses.TestInvitation": "fas fa-paper-plane"
    },
   "hide_apps": ["auth", "admin", "sessions", "authtoken"],  # lazımsız apps
    "hide_models": [
        "auth.Token",  # Token modelini gizlətmək üçün
        # Digər modelləri də əlavə edə bilərsən
    ],
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "show_sidebar": True,
    "navigation_expanded": True,
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'authApp.CustomUser'


ROOT_URLCONF = 'core.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT
        'rest_framework.authentication.SessionAuthentication',          # Browser/admin login
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # İstəyə görə dəyişə bilərsən
    ),
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

from django.utils.translation import gettext_lazy as _

LANGUAGES = (
    ('en', _('English')),
    ('az', _('Azerbaijani')),
)

MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Tokenin ömrü 10 saniyə
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh token ömrü (istəyə görə dəyiş)
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'


# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:5173")

PAYPAL_MODE=config("PAYPAL_MODE", default="live")


PAYPAL_LIVE_CLIENT_ID=config("PAYPAL_LIVE_CLIENT_ID", default=None)
PAYPAL_LIVE_CLIENT_SECRET=config("PAYPAL_LIVE_CLIENT_SECRET", default=None)

PAYPAL_WEBHOOK_ID=config("PAYPAL_WEBHOOK_ID", default=None)

PAYPAL_CLIENT_PROXY_ENABLED=config("PAYPAL_CLIENT_PROXY_ENABLED", default=False, cast=bool)

PAYPAL_RETURN_URL=config(
    "PAYPAL_RETURN_URL",
    default="http://localhost:2000/paypal/success"
)


PAYPAL_CANCEL_URL = config(
    "PAYPAL_CANCEL_URL",
    default="http://localhost:2000/paypal/cancel"
)

PAYPAL_CLIENT_ID=PAYPAL_LIVE_CLIENT_ID
PAYPAL_CLIENT_SECRET=PAYPAL_LIVE_CLIENT_SECRET
PAYPAL_API_BASE_URL="https://api-m.paypal.com"



# Email Ayarları
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.eu'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # Zoho 587 portu üçün TLS tələb edir
EMAIL_HOST_USER = 'noreply@octopus.com.az'
DEFAULT_FROM_EMAIL = 'Octopus <noreply@octopus.com.az>'
EMAIL_HOST_PASSWORD = 'm9jpU1TkDZjM'